import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {GroupGuard,duration,timeParts} from '../lib/core.mjs'
import {OneBotAdapter,normalize,unwrap} from '../lib/adapter.mjs'
import {validate} from '../lib/config.mjs'

const BOT='100000001',GROUP='200000001',ADMIN='300000001',USER='123456789',OTHER='987654321'
function fixture(t,{role='admin',botRole='admin',actorRole='admin',config={},group={},fetcher}={}){
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'groupguard-'));let now=Date.parse('2026-10-06T10:00:00Z'),counter=100
  const calls=[],replies=[],errors=[],members={[BOT]:{role:botRole},[ADMIN]:{role:actorRole},[USER]:{role:'member'},[OTHER]:{role}}
  const overrides={}
  const a=new OneBotAdapter(async(action,params)=>{
    calls.push({action,params})
    if(overrides[action])return overrides[action](params)
    if(action==='get_group_member_info')return {status:'ok',retcode:0,data:members[String(params.user_id)]}
    if(action==='get_group_member_list')return {status:'ok',retcode:0,data:Object.entries(members).map(([user_id,data])=>({user_id,...data}))}
    if(action==='send_group_msg'||action==='send_private_msg'){replies.push(params);return {status:'ok',retcode:0,data:{message_id:++counter}}}
    if(action==='get_msg')return {status:'ok',retcode:0,data:{group_id:GROUP,user_id:USER}}
    return {status:'ok',retcode:0,data:{}}
  })
  const engine=new GroupGuard(root,{now:()=>now,onError:e=>errors.push(String(e)),fetcher})
  engine.config.update(c=>Object.assign(c,config,{groups:[{groupId:GROUP,botId:BOT,enabled:true,...group}]}));engine.register(BOT,a)
  t.after(()=>{engine.close();fs.rmSync(root,{recursive:true,force:true})})
  const event={self_id:BOT,group_id:GROUP,user_id:ADMIN,post_type:'message',message:[],sender:{nickname:'管理员'}}
  return {root,a,engine,calls,replies,errors,members,overrides,event,advance:n=>{now+=n},setTime:n=>{now=n},run:(msg,extra={})=>{now+=1100;return engine.handle({...event,msg,message_id:++counter,...extra},a)}}
}
const lastText=f=>f.replies.at(-1)?.message?.[0]?.data?.text||''
test('接口仅承认明确成功，失败和缺状态不可假报成功',()=>{assert.equal(unwrap({status:'ok',retcode:0,data:2}),2);for(const r of [{status:'failed',retcode:100,message:'no'}, {data:2},null])assert.throws(()=>unwrap(r))})
test('正规化兼容 TRSS 与 OneBot 消息段/引用',()=>{const e=normalize({self_id:BOT,group_id:GROUP,user_id:USER,message:[{type:'text',data:{text:'#群管禁言 10分钟'}},{type:'at',data:{qq:OTHER}},{type:'reply',data:{id:42}}]});assert.equal(e.msg,'#群管禁言 10分钟');assert.deepEqual(e.at,[OTHER]);assert.equal(e.replyId,'42')})
test('中文时长、单位、上下界',()=>{assert.equal(duration('十五分钟'),900);assert.equal(duration('2天'),172800);assert.throws(()=>duration('31天'));assert.throws(()=>duration('0分钟'));assert.throws(()=>duration('x'))})
test('严格配置拒绝危险边界和空答案，不覆盖原配置',t=>{const f=fixture(t);for(const patch of [{requestExpireMinutes:0},{inviteMode:'oops'},{masters:['fake']},{timezone:'bad'}])assert.throws(()=>f.engine.config.update(c=>Object.assign(c,patch)));assert.throws(()=>f.engine.config.setGroup(BOT,GROUP,g=>{g.joinMode='answer'}));assert.equal(f.engine.config.read().requestExpireMinutes,5)})
test('帮助无管理权限可见；普通群消息不被拦截',async t=>{const f=fixture(t,{actorRole:'member'});assert.equal(await f.run('普通聊天'),false);assert.equal(await f.run('#群管帮助'),true);assert.match(lastText(f),/独立|群卫/);assert.equal(f.calls.some(x=>x.action==='set_group_ban'),false)})
test('成员不能设置、禁言或群黑名单',async t=>{const f=fixture(t,{actorRole:'member'});await f.run('#群管禁言 '+USER+' 1分钟');assert.match(lastText(f),/权限/);await f.run('#群管设置 likes 开');assert.equal(f.engine.config.group(BOT,GROUP).likes,false);await f.run('#群管群黑名单 添加 '+GROUP);assert.equal(f.engine.config.read().blackGroups.length,0)})
test('管理员不能开启关闭整个插件，群主可以',async t=>{const f=fixture(t);await f.run('#群管关闭');assert.equal(f.engine.config.group(BOT,GROUP).enabled,true);f.members[ADMIN].role='owner';await f.run('#群管关闭');assert.equal(f.engine.config.group(BOT,GROUP).enabled,false);await f.run('#群管禁言 '+USER+' 1分钟');assert.match(lastText(f),/尚未开启/)})
test('禁言/解禁带真实参数，机器人无管理权限拒绝',async t=>{const f=fixture(t);await f.run('#群管禁言 '+USER+' 十分钟');assert.deepEqual(f.calls.find(x=>x.action==='set_group_ban').params,{group_id:Number(GROUP),user_id:Number(USER),duration:600});await f.run('#群管解禁 '+USER);assert.equal(f.calls.filter(x=>x.action==='set_group_ban').at(-1).params.duration,0);f.members[BOT].role='member';await f.run('#群管踢 '+USER);assert.equal(f.calls.some(x=>x.action==='set_group_kick'),false)})
test('保护管理员、群主、自己和机器人，未发惩罚 API',async t=>{const f=fixture(t);for(const target of [OTHER,ADMIN,BOT])await f.run('#群管禁言 '+target+' 10分钟');assert.equal(f.calls.some(x=>x.action==='set_group_ban'),false);f.members[USER].role='owner';await f.run('#群管踢 '+USER);assert.equal(f.calls.some(x=>x.action==='set_group_kick'),false)})
test('任免管理员与头衔必须机器人群主，实际参数正确',async t=>{const f=fixture(t,{actorRole:'owner'});await f.run('#群管设管理 '+USER);assert.match(lastText(f),/机器人是群主/);f.members[BOT].role='owner';await f.run('#群管设管理 '+USER);await f.run('#群管撤管理 '+OTHER);await f.run('#群管头衔 '+USER+' 群成员');assert.equal(f.calls.filter(x=>x.action==='set_group_admin').length,2);assert.equal(f.calls.find(x=>x.action==='set_group_special_title').params.special_title,'群成员')})
test('接口拒绝禁言时不能回成功，审计不记录成功动作',async t=>{const f=fixture(t);f.overrides.set_group_ban=()=>({retcode:100,status:'failed',message:'权限不足'});await f.run('#群管禁言 '+USER+' 1分钟');assert.equal(lastText(f),'群卫：权限不足');assert.equal(f.engine.state.audit.some(x=>x.action==='禁言'),false)})
test('所有群设置即时生效并保留类型边界',async t=>{const f=fixture(t);await f.run('#群管设置 likes 开');assert.equal(f.engine.config.group(BOT,GROUP).likes,true);await f.run('#群管设置 rankLimit 51');assert.equal(f.engine.config.group(BOT,GROUP).rankLimit,10);await f.run('#群管黑名单 添加 '+USER);assert.deepEqual(f.engine.config.group(BOT,GROUP).blackUsers,[USER]);await f.run('#群管黑名单 删除 '+USER);assert.deepEqual(f.engine.config.group(BOT,GROUP).blackUsers,[])})
test('主人的全局设置必须私聊；私聊配置立即生效',async t=>{const f=fixture(t,{config:{masters:[ADMIN]}});await f.run('#群管全局 inviteMode manual');assert.equal(f.engine.config.read().inviteMode,'off');await f.run('#群管全局 inviteMode manual',{group_id:''});assert.equal(f.engine.config.read().inviteMode,'manual');await f.run('#群管群白名单 添加 '+GROUP,{group_id:''});assert.deepEqual(f.engine.config.read().whiteGroups,[GROUP])})
test('发言图片计数去重、跨机器人隔离、跨日保留昨日，重启保留',async t=>{const f=fixture(t);const event={...f.event,message_id:555,user_id:USER,message:[{type:'image'},{type:'image'}],sender:{nickname:'用户'}};await f.engine.handle(event,f.a);await f.engine.handle(event,f.a);const group=f.engine.getGroup(event);assert.equal(Object.values(group.days)[0][USER].count,1);assert.equal(Object.values(group.days)[0][USER].images,2);f.engine.config.setGroup('22222222',GROUP,g=>{g.enabled=true});await f.engine.handle({...event,self_id:'22222222'},f.a);assert.equal(Object.keys(f.engine.state.groups).length,2);f.advance(86400000);await f.run('#群管昨日榜');assert.match(lastText(f),/用户.*1条/);f.engine.save();const reloaded=new GroupGuard(f.root);assert.equal(Object.keys(reloaded.state.groups).length,2);reloaded.close()})
test('批量撤回限量、过期、部分失败准确计数，失败记录可重试',async t=>{const f=fixture(t,{group:{recallLimit:3,recallWindowMinutes:2}});const s=f.engine.getGroup(f.event);s.history=[{id:'1',user:USER,time:Date.parse('2026-10-06T09:00:00Z')},{id:'2',user:USER,time:Date.parse('2026-10-06T10:00:00Z')},{id:'3',user:USER,time:Date.parse('2026-10-06T10:00:00Z')}];f.overrides.delete_msg=p=>p.message_id==='2'?{status:'failed',retcode:1}:{status:'ok',retcode:0};await f.run('#群管撤回 '+USER+' 3');assert.match(lastText(f),/成功1条，失败1条/);assert.equal(s.history.some(x=>x.id==='2'),true);const n=f.calls.filter(x=>x.action==='delete_msg').length;await f.run('#群管撤回 '+USER+' 4');assert.equal(f.calls.filter(x=>x.action==='delete_msg').length,n)})
test('引用撤回不能跨群或撤回管理员消息',async t=>{const f=fixture(t);f.overrides.get_msg=()=>({status:'ok',retcode:0,data:{group_id:'11111111',user_id:USER}});await f.run('#群管撤回',{message:[{type:'reply',data:{id:42}}]});assert.match(lastText(f),/本群消息/);f.overrides.get_msg=()=>({status:'ok',retcode:0,data:{group_id:GROUP,user_id:OTHER}});await f.run('#群管撤回',{message:[{type:'reply',data:{id:42}}]});assert.equal(f.calls.some(x=>x.action==='delete_msg'),false)})
test('邀请审核默认完全不接管；黑名单优先于白名单',async t=>{const f=fixture(t,{config:{blackGroups:[GROUP],whiteGroups:[GROUP]}});await f.run('',{post_type:'request',request_type:'group',sub_type:'invite',flag:'a'});assert.equal(f.calls.some(x=>x.action==='set_group_add_request'),false);f.engine.config.update(c=>{c.inviteMode='manual'});await f.run('',{post_type:'request',request_type:'group',sub_type:'invite',flag:'b'});assert.equal(f.calls.find(x=>x.action==='set_group_add_request').params.approve,false)})
test('人工申请绑定账号/通知群/引用，外群伪造引用无法审核',async t=>{const f=fixture(t,{config:{inviteMode:'manual',managementGroups:[GROUP]}});await f.run('',{post_type:'request',request_type:'group',sub_type:'invite',flag:'flag',user_id:USER});const p=f.engine.state.pending[0];assert.equal(p.notices.length,1);await f.run('#群管同意',{message:[{type:'reply',data:{id:p.notices[0].id}}],group_id:'11111111'});assert.equal(f.calls.some(x=>x.action==='set_group_add_request'),false);await f.run('#确认加群',{message:[{type:'reply',data:{id:p.notices[0].id}}]});assert.equal(f.calls.find(x=>x.action==='set_group_add_request').params.approve,true);assert.equal(f.engine.state.pending.length,0)})
test('过期、重复请求与最大队列，过期不擅自拒绝 QQ 请求',async t=>{const f=fixture(t,{config:{inviteMode:'manual',managementGroups:[GROUP],maxPendingRequests:1}});const req={post_type:'request',request_type:'group',sub_type:'invite',flag:'one',user_id:USER};await f.run('',req);await f.run('',req);assert.equal(f.engine.state.pending.length,1);await f.run('',{...req,flag:'two'});assert.equal(f.engine.state.pending.length,1);f.advance(301000);await f.run('#群管待审核');assert.equal(f.engine.state.pending.length,0);assert.equal(f.calls.some(x=>x.action==='set_group_add_request'),false)})
test('人工审核 API 失败保留待审核项可以重试',async t=>{const f=fixture(t,{group:{joinMode:'manual'}});await f.run('',{post_type:'request',request_type:'group',sub_type:'add',flag:'fail',user_id:USER});const p=f.engine.state.pending[0];f.overrides.set_group_add_request=()=>({status:'failed',retcode:1,message:'try later'});await f.run('#群管同意 '+p.id);assert.equal(f.engine.state.pending.length,1);delete f.overrides.set_group_add_request;await f.run('#群管拒绝 '+p.id);assert.equal(f.engine.state.pending.length,0)})
test('入群答案精确匹配、等级不足拒绝、未知等级转人工',async t=>{const f=fixture(t,{group:{joinMode:'answer',answers:['正确答案'],exactMatch:true,minLevel:25}});const req={post_type:'request',request_type:'group',sub_type:'add',user_id:USER,comment:'问题：密码\n答案：正确答案'};f.overrides.get_stranger_info=()=>({status:'ok',retcode:0,data:{qqLevel:26}});await f.run('',{...req,flag:'1'});assert.equal(f.calls.filter(x=>x.action==='set_group_add_request').at(-1).params.approve,true);f.overrides.get_stranger_info=()=>({status:'ok',retcode:0,data:{level:10}});await f.run('',{...req,flag:'2'});assert.equal(f.calls.filter(x=>x.action==='set_group_add_request').at(-1).params.approve,false);f.overrides.get_stranger_info=()=>({status:'ok',retcode:0,data:{}});await f.run('',{...req,flag:'3'});assert.equal(f.engine.state.pending.length,1)})
test('入群成员黑白名单优先策略；离群可选拉黑和通知',async t=>{const f=fixture(t,{group:{joinMode:'manual',blackUsers:[USER],whiteUsers:[USER],autoBlacklistOnLeave:true,leaveEnabled:true}});await f.run('',{post_type:'request',request_type:'group',sub_type:'add',flag:'black',user_id:USER});assert.equal(f.calls.find(x=>x.action==='set_group_add_request').params.approve,false);await f.run('',{post_type:'notice',notice_type:'group_decrease',user_id:OTHER});assert.equal(f.engine.config.group(BOT,GROUP).blackUsers.includes(OTHER),true);assert.match(lastText(f),/离开/)})
test('自动退群默认关闭且管理群/白名单/主人/机器人群主豁免',async t=>{const f=fixture(t);await f.engine.autoQuit(f.event,f.a,f.engine.config.read());assert.equal(f.calls.some(x=>x.action==='set_group_leave'),false);f.engine.config.update(c=>{c.autoQuitEnabled=true;c.managementGroups=[GROUP]});await f.engine.autoQuit(f.event,f.a,f.engine.config.read());assert.equal(f.calls.some(x=>x.action==='set_group_leave'),false);f.engine.config.update(c=>{c.managementGroups=[];c.masters=[ADMIN]});await f.engine.autoQuit(f.event,f.a,f.engine.config.read());assert.equal(f.calls.some(x=>x.action==='set_group_leave'),false);f.engine.config.update(c=>{c.masters=[]});await f.engine.autoQuit(f.event,f.a,f.engine.config.read());assert.equal(f.calls.some(x=>x.action==='set_group_leave'),true)})
test('定时禁言/解禁准确一次，禁用群不执行，任务失败写日志',async t=>{const f=fixture(t,{group:{scheduledMute:true,muteTime:'18:00',unmuteTime:'19:00'}});await f.engine.tick();await f.engine.tick();assert.equal(f.calls.filter(x=>x.action==='set_group_whole_ban').length,1);f.advance(3600000);await f.engine.tick();assert.equal(f.calls.filter(x=>x.action==='set_group_whole_ban').at(-1).params.enable,false);f.engine.config.setGroup(BOT,GROUP,g=>{g.enabled=false});f.advance(86400000);await f.engine.tick();assert.equal(f.calls.filter(x=>x.action==='set_group_whole_ban').length,2)})
test('日报未配置明确提示，API 超时/格式错误不静默成功',async t=>{const f=fixture(t,{fetcher:async()=>({ok:true,json:async()=>({data:{news:['消息1','消息2']}})})});await f.run('#群管日报');assert.match(lastText(f),/未配置/);f.engine.config.update(c=>{c.dailyApi='https://example.test/news'});await f.run('#群管日报');assert.equal(lastText(f),'消息1\n消息2');f.engine.fetcher=async()=>({ok:false,status:500});await f.run('#群管日报');assert.match(lastText(f),/HTTP 500/)})
test('点赞按机器人/用户/日去重，接口失败允许重试',async t=>{const f=fixture(t,{group:{likes:true}});await f.run('#群管赞我');await f.run('#群管赞我');assert.equal(f.calls.filter(x=>x.action==='send_like').length,1);f.advance(86400000);await f.run('#群管赞我');assert.equal(f.calls.filter(x=>x.action==='send_like').length,2)})
test('时区跨日统计和调度一致',()=>{const p=timeParts(Date.parse('2026-10-06T16:01:00Z'),'Asia/Shanghai');assert.deepEqual(p,{day:'2026-10-07',month:'2026-10',time:'00:01'})})
